var name ="tricky dicky";
var jump_force =37;
var agility =100;
var speed =210;
var lives =7;
var ammo_type ="762 rifle";
var ammo_count =420;
var vehicle ="toyota supra";
var gasp_power =3;
var all_acces_pass =true;

console.log("name: " + name);
console.log("jump force: " + jump_force);
console.log("agility: " + agility);
console.log("speed: " + speed);
console.log("lives: " + lives);
console.log("ammo type: " + ammo_type);
console.log("ammo count: " + ammo_count);
console.log("vehicle: " + vehicle);
console.log("gasp power: " + gasp_power);
console.log("all acces pass: " + all_acces_pass);